version: "3.9"
services:
  run:
    container_name: guitarapp_deploy_run
    build:
      context: .
      dockerfile: Deploy.Dockerfile
      target: run
    environment:
      APP_ENV: ${APP_ENV}
      COLOUR: ${COLOUR}
      MANIFEST_S3_PATH: ${MANIFEST_S3_PATH}
      DEPLOYED_CONFIG_S3_PATH: ${DEPLOYED_CONFIG_S3_PATH}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_ACCOUNT: ${AWS_ACCOUNT}
      # some cloudfront features are only available in us-east-1
      AWS_REGION: us-east-1